import { test } from 'node:test';
import assert from 'node:assert/strict';
import { renderDoc, RenderError, detectLang } from '../src/render.js';
import { ParseError } from '../src/parse.js';

const SRC = `---
title: 测试页
subtitle: 副标题
source: example.org
---
导语 **加粗**。

## A 表格 {span=2 meta="Section 3"}
| 形式 | 状态 |
|---|---|
| 命令式 | ok 已批准 |
| 进行时 | no |

## 原始块
\`\`\`html
<div class="raw-x">raw</div>
\`\`\`
\`\`\`python
print("<x>")
\`\`\`
`;

test('render: emits complete single-file HTML with theme attrs and viewport', () => {
  const { html, meta } = renderDoc(SRC);
  assert.match(html, /^<!doctype html>/);
  assert.match(html, /<html lang="zh-CN" data-theme="blueprint" data-mode="auto">/);
  assert.match(html, /name="viewport"/);
  assert.equal(meta.template, 'sheet');
});

test('render: zero external deps - no http(s) scripts, styles, or fonts', () => {
  const { html } = renderDoc(SRC);
  assert.doesNotMatch(html, /<script[^>]+src=/);
  assert.doesNotMatch(html, /<link[^>]+href=/);
  assert.doesNotMatch(html, /@import|url\(\s*['"]?https?:/);
});

test('render: panel ID, title, meta, span take effect', () => {
  const { html } = renderDoc(SRC);
  assert.match(html, /id="panel-A" style="grid-column: span 2"/);
  assert.match(html, /<span class="am-panel-meta">Section 3<\/span>/);
  assert.match(html, /<h2>原始块<\/h2>/);
});

test('render: header has title, subtitle, extra meta, lead', () => {
  const { html } = renderDoc(SRC);
  assert.match(html, /<h1>测试页<\/h1>/);
  assert.match(html, /am-sub">副标题/);
  assert.match(html, /<b>source<\/b>example.org/);
  assert.match(html, /<strong>加粗<\/strong>/);
});

test('render: table status words render as badges', () => {
  const { html } = renderDoc(SRC);
  assert.match(html, /am-status--ok"><span class="am-status-icon" aria-hidden="true">✓<\/span>已批准/);
  assert.match(html, /am-status--no/);
  assert.match(html, /am-table-wrap/);
});

test('render: html fences embed raw; unknown langs become escaped code blocks', () => {
  const { html } = renderDoc(SRC);
  assert.match(html, /<div class="raw-x">raw<\/div>/);
  assert.match(html, /<pre class="am-code"><code data-lang="python">print\(&quot;&lt;x&gt;&quot;\)<\/code><\/pre>/);
});

test('render: escaped source embeds in hidden textarea, round-trips exactly', () => {
  const src = '## A\n```html\n<script>x</script></textarea>\n```';
  const { html } = renderDoc(src);
  const embedded = html.match(/<textarea id="am-source" hidden readonly aria-hidden="true">([\s\S]*?)<\/textarea>/)[1];
  assert.doesNotMatch(embedded, /<\/?(script|textarea)/);
  const unescaped = embedded.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&amp;/g, '&');
  assert.equal(unescaped, src);
});

test('render: footer colophon has version and timestamp', () => {
  assert.match(renderDoc('## A\nx').html, /<footer class="am-colophon">Generated by SheetPress \d+\.\d+\.\d+ · \d{4}-\d{2}-\d{2} \d{2}:\d{2}<\/footer>/);
});

test('render: CLI overrides apply and validate', () => {
  const { html } = renderDoc(SRC, { theme: 'shadcn', template: 'doc' });
  assert.match(html, /data-theme="shadcn"/);
  assert.match(html, /class="am-doc"/);
  assert.throws(() => renderDoc(SRC, { theme: 'x' }), ParseError);
});

test('render: doc template generates TOC at 3+ panels', () => {
  const { html } = renderDoc('---\ntemplate: doc\n---\n## 一\na\n## 二\nb\n## 三\nc');
  assert.match(html, /<nav class="am-toc"/);
  assert.match(html, /href="#panel-C">C · 三/);
});

test('render: English docs use English UI copy', () => {
  const { html } = renderDoc('# Hello world\n## A Overview\nThis is a plain English page about things.');
  assert.match(html, /<html lang="en"/);
  assert.match(html, /Copy source/);
});

test('detectLang: judges by Chinese-character ratio', () => {
  assert.equal(detectLang('全中文内容'), 'zh');
  assert.equal(detectLang('all english words here'), 'en');
});

test('render: counts panels and components', () => {
  const { stats } = renderDoc(SRC);
  assert.equal(stats.panels, 2);
});

test('RenderError type exists', () => {
  assert.equal(new RenderError('x', { line: 3 }).line, 3);
});

test('render: rows attr spans rows vertically; bare attr drops the panel header', () => {
  const { html } = renderDoc('## A 高面板 {rows=2 span=2}\nx\n## B {bare}\ny');
  assert.match(html, /id="panel-A" style="grid-column: span 2; grid-row: span 2"/);
  assert.match(html, /<section class="am-panel am-panel--bare" id="panel-B">\n<div class="am-panel-body">/);
});

test('sheet: panels stretch to fill the row when the next one will not fit, no gaps', async () => {
  const { fillRows } = await import('../src/templates/sheet.js');
  const P = (span) => ({ attrs: span ? { span } : {} });
  // cols=2: A(2) | B(1) C(2) -> C does not fit after B, so B stretches to 2
  assert.deepEqual(fillRows([P(2), P(), P(2), P()], 2), [2, 2, 2, 2]);
  // cols=3: A(1) B(1) C(2) -> A and B take 2, C does not fit, so B stretches to 2; C(2) is the last row, so it stretches to fill 3
  assert.deepEqual(fillRows([P(), P(), P(2)], 3), [1, 2, 3]);
  // unchanged when the row is exactly full
  assert.deepEqual(fillRows([P(), P(2), P(3)], 3), [1, 2, 3]);
  // no adjustment when rows spans are used; keep the author's layout
  assert.deepEqual(fillRows([{ attrs: { rows: 2 } }, P(), P(2)], 3), [1, 1, 2]);
});

test('sheet: auto-stretch shows up in rendered output', () => {
  const { html } = renderDoc('---\ncols: 2\n---\n## A {span=2}\nx\n## B\ny\n## C {span=2}\nz');
  assert.match(html, /id="panel-B" style="grid-column: span 2"/);
});
