// Bundle the CLI into a single file: skills/sheetpress/scripts/sp.mjs.
// It ships with the skill directory: after `npx skills add` or a marketplace install, it runs with just Node, no `npm install` needed.
import { build } from 'esbuild';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8');

// Replace src/assets.js with inline strings to drop the runtime dependency on files on disk.
const inlineAssets = {
  name: 'inline-assets',
  setup(b) {
    b.onLoad({ filter: /src[\\/]assets\.js$/ }, () => ({
      loader: 'js',
      contents: [
        `export const VERSION = ${JSON.stringify(JSON.parse(read('../package.json')).version)};`,
        `export const BASE_CSS = ${JSON.stringify(read('../src/themes/base.css'))};`,
        `export const RUNTIME_JS = ${JSON.stringify(read('../src/runtime/page.js'))};`,
      ].join('\n'),
    }));
  },
};

await build({
  entryPoints: [fileURLToPath(new URL('../bin/am.js', import.meta.url))],
  outfile: fileURLToPath(new URL('../skills/sheetpress/scripts/sp.mjs', import.meta.url)),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  legalComments: 'eof',
  banner: { js: '// SheetPress CLI — generated by scripts/build.mjs, do not edit. Source: https://github.com/10xdev4u-alt/sheetpress (fork of https://github.com/QingYunA/answer-me-with-html)' },
  plugins: [inlineAssets],
  logLevel: 'info',
});
